### ISSUE TITLE
2u/up queries reproduction with CQD @ KGReasoning

### ISSUE THREAD

**Issue by pminervini** [pminervini/KGReasoning#1]
See https://github.com/uclnlp/cqd/issues/7

@migalkin let me keep this open until I add the instructions for reproducing the results

**Comment by pminervini** [comment]
@migalkin done! here you go: https://github.com/pminervini/KGReasoning/blob/main/CQD.md

If you think that works, I can close this issue :) WYT?

**Comment by migalkin** [comment]
Wonderful! Yes, can be closed now
