### ISSUE TITLE
Error while running CQD model.

### ISSUE THREAD

**Issue by YaooXu** [pminervini/KGReasoning#2]
Could you offer a command to train and test CQD model?
I have tried to **train** CQD model with this command: 
```
main.py --cuda --do_train --do_valid --do_test --data_path=data/FB15k-237-betae --print_on_screen --use-qa-iterator -n=128 -b=512 -d=800 -g=24 -lr=0.0001 --max_steps=450001 --cpu_num=1 --geo=cqd --valid_steps=15000 --tasks=1p
```

But it reported that ```RuntimeError: Adam does not support sparse gradients, please consider SparseAdam instead```

Is this as expected? If it is, can I only replace Adam with SparseAdam?

Thanks~

**Comment by YaooXu** [comment]
It seems that I should set `sparse=False` in https://github.com/pminervini/KGReasoning/blob/main/cqd/base.py#L59 to train CQD model.

**Comment by pminervini** [comment]
Sorry for the delay! Looking into this rn

**Comment by pminervini** [comment]
You were right with your fix, thank you! Sorted!
